version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

commands:
  prepare:
    description: "Install dependencies"
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: '[ -d "./node_modules" ] || npm ci'
      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  build:
    working_directory: ~/create-settings
    docker:
      - image: circleci/node:10
    steps:
      - prepare
      - run: npm run build

  test-node-10:
    working_directory: ~/create-settings
    docker:
      - image: circleci/node:10
    steps:
      - prepare
      - run:
          command: npm test
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-node-10
